### ISSUE TITLE
Permission for history

### ISSUE THREAD

**Issue by amadensor** [codenotary/immudb-py#13] opened 2020-12-13 22:24 UTC
When using a get for the same key, I get results.   When using immuclient as the same user, history works.  When using history from the Python connector, I get:

grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:<
status = StatusCode.UNKNOWN
details = "you do not have permission for this operation"
debug_error_string = "{"created":"@1607898051.288363185","description":"Error received from peer ipv6:[::1]:3322","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"you do not have permission for this operation","grpc_status":2}"
>

Note:   I was unable to install via pip (older version without history instead was installed) so I grabbed current master from GitHub.

**Comment by SimoneLazzaris** [comment] 2020-12-14 07:24
@amadensor , what are permission for that user?

**Comment by amadensor** [comment] 2020-12-14 14:09
immuadmin-v0.8.0-linux-amd64
2  immuvote  true    immuvote   Read/Write    immudb      2020-12-12 11:47:13.653569786 -0700 MST

**Comment by SimoneLazzaris** [comment] 2020-12-14 16:36
Bug confirmed. I think that's immudb that is giving immudb client that response. Will check with immudb developers. Thanks for the report.

**Comment by SimoneLazzaris** [comment] 2020-12-14 16:39
This is due to a change in the immudb api. Please try with feat/nosv branch, that mirrors last modification schema from immudb and will be merged soon.

**Comment by amadensor** [comment] 2020-12-14 16:43
Thank you.   I will test that ASAP.

**Comment by amadensor** [comment] 2020-12-14 16:54
It now returns a list.   Thank you.   I will now adjust my code to handle the list.

**Closed** 2020-12-14 17:00 UTC
Labels: bug
